print("Village 1 chance of same sex:", chance_homophily(sex1))
print("Village 2 chance of same sex:", chance_homophily(sex2))
print("Village 1 chance of same caste:", chance_homophily(caste1))
print("Village 2 chance of same caste:", chance_homophily(caste2))
print("Village 1 chance of same religion:", chance_homophily(religion1))
print("Village 2 chance of same religion:", chance_homophily(religion2))